export const CREATE_ARTICLE_COMMENT_SUCCESS = 'CREATE_ARTICLE_COMMENT_SUCCESS';
export const CREATE_ARTICLE_COMMENT_FAILURE = 'CREATE_ARTICLE_COMMENT_FAILURE';

export const GET_ARTICLE_COMMENT_SUCCESS = 'GET_ARTICLE_COMMENT_SUCCESS';
export const GET_ARTICLE_COMMENT_FAILURE = 'GET_ARTICLE_COMMENT_FAILURE';
