export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';
export const GET_FOLLOWINGS_SUCCESS = 'GET_FOLLOWINGS_SUCCESS';
export const GET_FOLLOWINGS_FAILURE = 'GET_FOLLOWINGS_FAILURE';
export const FOLLOW_UNFOLLOW_SUCCESS = 'FOLLOW_UNFOLLOW_SUCCESS';
export const FOLLOW_UNFOLLOW_FAILURE = 'FOLLOW_UNFOLLOW_FAILURE';
