export const SET_ARTICLE_TITLE = 'SET_ARTICLE_TITLE';
export const SET_ARTICLE_BODY = 'SET_ARTICLE_BODY';
export const SET_ARTICLE_TAGS = 'SET_ARTICLE_TAGS';
export const SET_ARTICLE_IMAGES = 'SET_ARTICLE_IMAGES';
export const SET_ARTICLE_ERROR = 'SET_ARTICLE_ERROR';
export const SET_ARTICLE_PUBLISH = 'SET_ARTICLE_PUBLISH';
export const SET_ARTICLE_ON_UPDATE = 'SET_ARTICLE_ON_UPDATE';
